---

- name: Reload daemon
  systemd: 
    daemon_reload: yes

# - name: Restart kafka service
#   service:
#     name: kafka
#     state: restarted

# - name: Restart zookeeper systemd
#   systemd:
#     name: zookeeper
#     state: restarted
#     enabled: yes
#     daemon_reload: yes

- name: Restart kafka systemd
  systemd:
    name: kafka
    state: restarted
    enabled: yes
    daemon_reload: yes

# - name: Reload initd
#   command: initctl reload-configuration