{
 "title": "Evolution Gaming Kafka dashboard",
 "description": "Monitoring Kafka Broker and Input-Ouput Services",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hosts", "query": "label_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "Kafka broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Topic Messages Count",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_log_log_logendoffset{instance=\"192.168.30.101:7071\", job=\"kafka-server\", partition=\"0\", topic=\"input\"}"
      }
     ]
    },
    {
     "title": "Output Topic Messages Count",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_log_log_logendoffset{instance=\"192.168.30.101:7071\", job=\"kafka-server\", partition=\"0\", topic=\"output\"}"
      }
     ]
    },
    {
     "title": "Produce request rate by topic",
     "type": "graph",
     "description": "TotalProduceRequestsPerSec",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_totalproducerequests_total{topic != \"\"}[1m])",
       "legendFormat": "({{ instance }} - topic:  {{ topic }}) success"
      },
      {
       "expr": "rate(kafka_server_brokertopicmetrics_failedproducerequests_total{topic != \"\"}[1m])",
       "legendFormat": "({{ instance }} - topic:  {{ topic }}) errors"
      }
     ]
    },
    {
     "title": "Kafka Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-server\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka network total request rate",
     "type": "graph",
     "description": "kafka.network:type=RequestMetrics,name=RequestsPerSec,request={Produce|FetchConsumer|FetchFollower}",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_network_requestmetrics_requests_total{request=~\"Produce|FetchConsumer|FetchFollower\"}[1m])",
       "legendFormat": "({{ instance }}) {{ request }}"
      }
     ]
    },
    {
     "title": "Consume request rate by topic",
     "type": "graph",
     "description": "TotalFetchRequestsPerSec",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic != \"\"}[1m])",
       "legendFormat": "({{ instance }} - topic:  {{ topic }}) success"
      },
      {
       "expr": "rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{topic != \"\"}[1m])",
       "legendFormat": "({{ instance }} - topic:  {{ topic }}) errors"
      }
     ]
    },
    {
     "title": "Bytes In Per Topic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka-server\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Topic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka-server\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Consumer & Producer Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Producer Service Counter",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "python_evolution_producer_counter_total"
      }
     ]
    },
    {
     "title": "Kafka Consumer Service Counter",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "python_evolution_consumer_counter_total"
      }
     ]
    },
    {
     "title": "Kafka Producer Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-producer\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-consumer\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}