- name: KAFKA | Create kafka topics
  command: >
    {{ kafka_install_path }}/bin/kafka-topics.sh
    --zookeeper localhost:2181
    --topic {{ item.name }}
    --partitions {{ item.partitions }}
    --replication-factor {{ item.replicas }}
    --create
    --if-not-exists
    --force
  with_items:
    - "{{ kafka_topics }}"

# - name: KAFKA | Check Topics
#   command: >
#     {{ kafka_install_path }}/bin/kafka-topics.sh
#     --zookeeper localhost:2181
#     --topic {{ item.name }}
#     --describe
#   with_items:
#     - "{{ kafka_topics }}"